version: '3.9'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # Porta de acesso à API do MinIO
      - "9001:9001" # Porta de acesso ao console do MinIO
    volumes:
      - ./data:/data # Mapeie o diretório local "data" para armazenar os arquivos no MinIO
    command: server /data --console-address ":9001"

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8080:8080" # Porta para acessar o Trino

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotify
    ports:
      - "5432:5432" # Porta padrão para conexões PostgreSQL
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Diretório persistente para dados do Postgres

  superset:
    image: apache/superset
    container_name: superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "your_secret_key"
      SUPERSET_DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/spotify"
    ports:
      - "8088:8088" # Porta de acesso ao Superset
    depends_on:
      - postgres # Garante que o PostgreSQL será iniciado antes do Superset

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify_app
    env_file:
      - .env
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    depends_on:
      - minio
    command: python /app/scripts/main.py

